/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ablakok;

import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Verosffy
 */
public class MenuAblak extends javax.swing.JFrame {

    /**
     * Creates new form MenuAblak
     */
    static ArrayList<String> menukListaja; 

    public MenuAblak() {
        initComponents();
      
    }

    public static void menulistaElmento() {
        try {
            FileOutputStream file = new FileOutputStream("src\\datfileok\\menukListaja.dat");
            ObjectOutputStream kimeno = new ObjectOutputStream(file);
            for (int i = 0; i < menukListaja.size(); i++) {
                String get = menukListaja.get(i);
                kimeno.writeObject(get);
            }
            kimeno.close();
            
        } catch (FileNotFoundException e) {
            
        } catch (IOException ex) {
            Logger.getLogger(MenuAblak.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public static void menulistaBehozo() {
        try {
            FileInputStream file = new FileInputStream("src\\datfileok\\menukListaja.dat");
            ObjectInputStream bejovoLista = new ObjectInputStream(file);
            boolean endOfFile = false;
            menukListaja=new ArrayList<>();
            while (!endOfFile) {
                try {
                    menukListaja.add((String) bejovoLista.readObject());
                } catch (EOFException e) {
                    endOfFile = !endOfFile;                    
                }
            }
            
        } catch (FileNotFoundException ex) {
            
        } catch (IOException ex) {
            
        } catch (ClassNotFoundException ex) {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        FunkciokMenu = new javax.swing.JMenu();
        VMGyakMenuPont = new javax.swing.JMenuItem();
        MenuAjMenuPont = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        UjMenuMenuPont = new javax.swing.JMenuItem();
        MenuSzerkMenuPont = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FunkciokMenu.setText("Funkciók");

        VMGyakMenuPont.setText("Választott menuk gyakorisága");
        FunkciokMenu.add(VMGyakMenuPont);

        MenuAjMenuPont.setText("Menu ajánlat");
        FunkciokMenu.add(MenuAjMenuPont);

        jMenuBar1.add(FunkciokMenu);

        jMenu2.setText("Szerkesztés");

        UjMenuMenuPont.setText("Új menu létrehozása");
        UjMenuMenuPont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UjMenuMenuPontActionPerformed(evt);
            }
        });
        jMenu2.add(UjMenuMenuPont);

        MenuSzerkMenuPont.setText("Meglévő menu szerkesztése");
        MenuSzerkMenuPont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSzerkMenuPontActionPerformed(evt);
            }
        });
        jMenu2.add(MenuSzerkMenuPont);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UjMenuMenuPontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UjMenuMenuPontActionPerformed
        new UjMenuLetrehozasa().setVisible(true);
    }//GEN-LAST:event_UjMenuMenuPontActionPerformed

    private void MenuSzerkMenuPontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSzerkMenuPontActionPerformed
       new MenuSzerkesztese().setVisible(true);
    }//GEN-LAST:event_MenuSzerkMenuPontActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAblak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAblak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAblak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAblak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAblak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu FunkciokMenu;
    private javax.swing.JMenuItem MenuAjMenuPont;
    private javax.swing.JMenuItem MenuSzerkMenuPont;
    private javax.swing.JMenuItem UjMenuMenuPont;
    private javax.swing.JMenuItem VMGyakMenuPont;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    // End of variables declaration//GEN-END:variables
}
